<?php

DEFINE("SLS_ID_PREFIX", "0xSID");
DEFINE("SLS_HASH_PREFIX", "0xSH");
DEFINE("SLS_PUBLIC_KEY_PREFIX", "0xSPB");
DEFINE("SLS_PRIVATE_KEY_PREFIX", "0xSPV");
DEFINE("SKYID_INSTANCE", $_ENV["SKYID_INSTANCE"]);
DEFINE("PRIVATE_KEY_GEN_LENGTH", 256);
